# Generated by Django 4.0.3 on 2022-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
