# Generated by Django 4.0.3 on 2022-03-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(null=True, upload_to='static/uploads/'),
        ),
    ]
