# Generated by Django 4.0.3 on 2022-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=255)),
                ('facilities', models.TextField(null=True)),
                ('star_rating', models.IntegerField(null=True)),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
    ]
