# Generated by Django 4.0.3 on 2022-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
